import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const html = `<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>تقييم أداء الموظفين</title><link rel="stylesheet" href="/unified-font.css">
<style>*,*:before,*:after{box-sizing:border-box}body{margin:0;min-height:100vh;background:#2445d9;font-family:var(--app-font);color:#17213c;display:grid;place-items:center;padding:24px}.wrap{width:min(460px,100%);text-align:center}.brand{color:white;margin-bottom:28px}.drop{font-size:56px;line-height:1}.brand h1{font-size:24px;margin:7px 0 3px}.brand p{margin:0;font-size:13px;opacity:.9}.card{background:#fff;border-radius:28px;padding:28px 30px;box-shadow:0 20px 45px #10259b55;text-align:right}.title{font-weight:700;font-size:18px;margin-bottom:20px}.field{display:block;color:#77829a;font-size:13px;margin:15px 0 7px}.input{width:100%;height:45px;border:1px solid #d9deea;border-radius:13px;padding:0 14px;font-size:14px;outline:0;direction:ltr;text-align:left}.input:focus{border-color:#2445d9;box-shadow:0 0 0 3px #2445d918}.hint{font-size:12px;color:#8791a6;text-align:center;margin:22px 0}.btn{width:100%;height:50px;border:0;border-radius:14px;background:#2445d9;color:#fff;font-size:16px;font-weight:700;cursor:pointer}.btn:disabled{opacity:.65;cursor:wait}.err{min-height:18px;color:#c43232;font-size:12px;text-align:center;margin:10px 0 0}.forgot{display:block;margin:13px auto 0;border:0;background:none;color:#2445d9;cursor:pointer;font-size:13px}@media(max-width:480px){body{padding:16px}.card{padding:24px 20px;border-radius:22px}}</style></head>
<body><main class="wrap"><div class="brand"><div class="drop">◔</div><h1>تقييم أداء الموظفين</h1><p>شركة السويد التجارية</p></div><form class="card" id="login"><div class="title">تسجيل الدخول</div><label class="field" for="email">البريد الإلكتروني</label><input class="input" id="email" type="email" autocomplete="email" required placeholder="name@company.com"><label class="field" for="password">كلمة المرور</label><input class="input" id="password" type="password" autocomplete="current-password" required placeholder="••••••••"><p class="hint">استخدم البريد الإلكتروني وكلمة المرور الخاصة بحسابك</p><button class="btn" id="submit" type="submit">دخول</button><div class="err" id="error" role="alert"></div><button class="forgot" type="button" onclick="location.href='/login?reset=1'">نسيت كلمة المرور؟</button></form></main><script>document.getElementById('login').addEventListener('submit',async e=>{e.preventDefault();const b=document.getElementById('submit'),x=document.getElementById('error');x.textContent='';b.disabled=true;b.textContent='جارٍ الدخول...';try{const r=await fetch('/api/app/auth/login',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'INVALID_CREDENTIALS');location.replace('/assessment')}catch(e){x.textContent=e.message==='RATE_LIMITED'?'محاولات كثيرة، حاول بعد 15 دقيقة':'البريد الإلكتروني أو كلمة المرور غير صحيحة';b.disabled=false;b.textContent='دخول'}});</script></body></html>`;

export function GET() {
  return new NextResponse(html.replace("location.replace('/assessment')", "location.replace('/')"), { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' } });
}
