import {NextRequest,NextResponse} from 'next/server';
import {z} from 'zod';
import {requireUser,jsonError,must,assertEmployeeAccess} from '@/server/context';
import {visibleEmployees} from '@/db/queries/security';
import {pool} from '@/db';
import {withNeonTransaction} from '@/lib/neon/admin';

const createSchema=z.object({full_name:z.string().trim().min(2),job_title_id:z.string().uuid().nullable().optional(),job_title_name:z.string().trim().min(1).nullable().optional(),email:z.string().email().nullable().optional(),phone:z.string().nullable().optional(),manager_id:z.string().uuid().nullable().optional()});
const updateSchema=z.object({id:z.string().uuid(),full_name:z.string().trim().min(2).optional(),job_title_id:z.string().uuid().nullable().optional(),job_title_name:z.string().trim().min(1).nullable().optional(),email:z.string().email().nullable().optional(),phone:z.string().nullable().optional(),status:z.enum(['active','leave','suspended','resigned','transferred','terminated']).optional()});
async function resolveTitle(org:string,id?:string|null,name?:string|null){if(id)return id;if(!name)return null;const r=await pool.query(`select id from public.job_titles where organization_id=$1::uuid and name=$2 and active=true and deleted_at is null limit 1`,[org,name]);return r.rows[0]?.id?String(r.rows[0].id):null;}

export async function GET(req:NextRequest){try{const c=await requireUser();must(c,'employees.view');const u=new URL(req.url);const r=await visibleEmployees(c,{limit:Number(u.searchParams.get('limit')||100),offset:Number(u.searchParams.get('offset')||0),search:u.searchParams.get('search')||''});return NextResponse.json({ok:true,employees:r.rows,pagination:{total:r.total,limit:r.limit,offset:r.offset,has_more:r.hasMore}});}catch(e){const x=jsonError(e);return NextResponse.json({ok:false,error:x.error},{status:x.status});}}

export async function POST(req:NextRequest){try{const c=await requireUser();must(c,'employees.create');const p=createSchema.parse(await req.json());const title=await resolveTitle(c.organizationId,p.job_title_id,p.job_title_name);if((p.job_title_id||p.job_title_name)&&!title)throw new Error('JOB_TITLE_NOT_FOUND');if(p.manager_id)await assertEmployeeAccess(c,p.manager_id);const num=`EMP-${Date.now()}-${Math.floor(Math.random()*10000).toString().padStart(4,'0')}`;const manager=p.manager_id??c.user.employeeId??null;let employee:any;
 await withNeonTransaction(async tx=>{const r=await tx.query(`insert into public.employees(organization_id,employee_number,full_name,email,phone,job_title_id,manager_id,status,created_by) values($1::uuid,$2,$3,$4,$5,$6::uuid,$7::uuid,'active',$8::uuid) returning id,employee_number,full_name,job_title_id,status`,[c.organizationId,num,p.full_name,p.email||null,p.phone||null,title,manager,c.user.id]);employee=r.rows[0];await tx.query(`insert into public.employee_assignments(employee_id,job_title_id,manager_id,effective_from,reason,is_current,created_by) values($1::uuid,$2::uuid,$3::uuid,current_date,$4,true,$5::uuid)`,[employee.id,title,manager,'إضافة موظف من واجهة التقييم',c.user.id]);await tx.query(`insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,new_values) values($1::uuid,$2::uuid,'employee.create','employee',$3::uuid,$4::jsonb)`,[c.organizationId,c.user.id,employee.id,JSON.stringify({full_name:p.full_name,job_title_id:title})]);});return NextResponse.json({ok:true,employee});}catch(e){const x=jsonError(e);return NextResponse.json({ok:false,error:x.error},{status:x.status});}}

export async function PATCH(req:NextRequest){try{const c=await requireUser();must(c,'employees.update');const body=await req.json();
 if(body?.action==='transfer'){
  const p=z.object({id:z.string().uuid(),branch_id:z.string().uuid().nullable().optional(),department_id:z.string().uuid().nullable().optional(),section_id:z.string().uuid().nullable().optional(),job_title_id:z.string().uuid().nullable().optional(),manager_id:z.string().uuid().nullable().optional(),supervisor_id:z.string().uuid().nullable().optional(),reason:z.string().trim().min(3)}).parse(body);await assertEmployeeAccess(c,p.id);if(p.manager_id)await assertEmployeeAccess(c,p.manager_id);if(p.supervisor_id)await assertEmployeeAccess(c,p.supervisor_id);let assignmentId='';
  await withNeonTransaction(async tx=>{const old=await tx.query(`select branch_id,department_id,section_id,job_title_id,manager_id,supervisor_id from public.employees where id=$1::uuid and organization_id=$2::uuid for update`,[p.id,c.organizationId]);if(!old.rows[0])throw Object.assign(new Error('FORBIDDEN'),{status:403});await tx.query(`update public.employee_assignments set is_current=false,effective_to=current_date where employee_id=$1::uuid and is_current=true`,[p.id]);const a=await tx.query(`insert into public.employee_assignments(employee_id,branch_id,department_id,section_id,job_title_id,manager_id,supervisor_id,effective_from,reason,is_current,created_by) values($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::uuid,$7::uuid,current_date,$8,true,$9::uuid) returning id`,[p.id,p.branch_id||null,p.department_id||null,p.section_id||null,p.job_title_id||null,p.manager_id||null,p.supervisor_id||null,p.reason,c.user.id]);assignmentId=String(a.rows[0].id);await tx.query(`update public.employees set branch_id=$2::uuid,department_id=$3::uuid,section_id=$4::uuid,job_title_id=$5::uuid,manager_id=$6::uuid,supervisor_id=$7::uuid,updated_at=now() where id=$1::uuid`,[p.id,p.branch_id||null,p.department_id||null,p.section_id||null,p.job_title_id||null,p.manager_id||null,p.supervisor_id||null]);await tx.query(`insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,old_values,new_values,reason) values($1::uuid,$2::uuid,'employee.transfer','employee',$3::uuid,$4::jsonb,$5::jsonb,$6)`,[c.organizationId,c.user.id,p.id,JSON.stringify(old.rows[0]),JSON.stringify(p),p.reason]);});return NextResponse.json({ok:true,assignment_id:assignmentId});
 }
 const p=updateSchema.parse(body);await assertEmployeeAccess(c,p.id);const title=await resolveTitle(c.organizationId,p.job_title_id,p.job_title_name);if((p.job_title_id||p.job_title_name)&&!title)throw new Error('JOB_TITLE_NOT_FOUND');let employee:any;await withNeonTransaction(async tx=>{const old=await tx.query(`select * from public.employees where id=$1::uuid and organization_id=$2::uuid for update`,[p.id,c.organizationId]);if(!old.rows[0])throw Object.assign(new Error('FORBIDDEN'),{status:403});const next={...old.rows[0],...p};if(p.job_title_id!==undefined||p.job_title_name!==undefined)next.job_title_id=title;const r=await tx.query(`update public.employees set full_name=coalesce($2,full_name),email=case when $3::boolean then $4 else email end,phone=case when $5::boolean then $6 else phone end,status=coalesce($7,status),job_title_id=case when $8::boolean then $9::uuid else job_title_id end,updated_at=now() where id=$1::uuid returning id,full_name,job_title_id,status`,[p.id,p.full_name??null,p.email!==undefined,p.email??null,p.phone!==undefined,p.phone??null,p.status??null,p.job_title_id!==undefined||p.job_title_name!==undefined,title]);employee=r.rows[0];if(p.job_title_id!==undefined||p.job_title_name!==undefined){await tx.query(`update public.employee_assignments set is_current=false,effective_to=current_date where employee_id=$1::uuid and is_current=true`,[p.id]);await tx.query(`insert into public.employee_assignments(employee_id,branch_id,department_id,section_id,job_title_id,manager_id,supervisor_id,effective_from,reason,is_current,created_by) select id,branch_id,department_id,section_id,job_title_id,manager_id,supervisor_id,current_date,$2,true,$3::uuid from public.employees where id=$1::uuid`,[p.id,'تعديل المسمى من واجهة التقييم',c.user.id]);}await tx.query(`insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,old_values,new_values) values($1::uuid,$2::uuid,'employee.update','employee',$3::uuid,$4::jsonb,$5::jsonb)`,[c.organizationId,c.user.id,p.id,JSON.stringify(old.rows[0]),JSON.stringify(employee)]);});return NextResponse.json({ok:true,employee});
 }catch(e){const x=jsonError(e);return NextResponse.json({ok:false,error:x.error},{status:x.status});}}

export async function DELETE(req:NextRequest){try{const c=await requireUser();must(c,'employees.delete');const id=z.string().uuid().parse(new URL(req.url).searchParams.get('id'));await assertEmployeeAccess(c,id);await withNeonTransaction(async tx=>{const old=await tx.query(`select id,full_name,status from public.employees where id=$1::uuid and organization_id=$2::uuid for update`,[id,c.organizationId]);if(!old.rows[0])throw Object.assign(new Error('FORBIDDEN'),{status:403});await tx.query(`update public.employees set status='terminated',work_end_date=current_date,deleted_at=coalesce(deleted_at,now()),updated_at=now() where id=$1::uuid`,[id]);await tx.query(`update public.employee_assignments set is_current=false,effective_to=current_date where employee_id=$1::uuid and is_current=true`,[id]);await tx.query(`insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,old_values) values($1::uuid,$2::uuid,'employee.soft_delete','employee',$3::uuid,$4::jsonb)`,[c.organizationId,c.user.id,id,JSON.stringify(old.rows[0])]);});return NextResponse.json({ok:true});}catch(e){const x=jsonError(e);return NextResponse.json({ok:false,error:x.error},{status:x.status});}}
