import {NextRequest,NextResponse} from 'next/server';import {z} from 'zod';import {requireUser,jsonError,must,can} from '@/server/context';import {pool} from '@/db';
function codeOf(p:any){return p.code&&p.code.trim()?p.code.trim():('AUTO_'+Date.now().toString(36).toUpperCase());}
export async function GET(){try{const c=await requireUser();if(!['branches.manage','departments.manage','sections.manage','job_titles.manage','roles.manage','settings.manage'].some((p)=>can(c,p)))throw Object.assign(new Error('FORBIDDEN'),{status:403});const [branches,depts,sections,titles,roles,perms,rolePerms,settings]=await Promise.all([
 pool.query(`select id,name,code,city,address,phone,active,manager_employee_id from public.branches where organization_id=$1::uuid and deleted_at is null order by name`,[c.organizationId]),pool.query(`select id,name,code,branch_id,parent_department_id,manager_employee_id,active from public.departments where organization_id=$1::uuid and deleted_at is null order by name`,[c.organizationId]),pool.query(`select id,name,code,department_id,manager_employee_id,active from public.sections where organization_id=$1::uuid and deleted_at is null order by name`,[c.organizationId]),pool.query(`select id,name,code,description,active from public.job_titles where organization_id=$1::uuid and deleted_at is null order by name`,[c.organizationId]),pool.query(`select id,code,name_ar,description,is_system,active from public.roles where (organization_id is null or organization_id=$1::uuid) order by name_ar`,[c.organizationId]),pool.query(`select id,code,name_ar,description from public.permissions order by code`),pool.query(`select rp.role_id,rp.permission_id from public.role_permissions rp join public.roles r on r.id=rp.role_id where r.organization_id is null or r.organization_id=$1::uuid`,[c.organizationId]),pool.query(`select id,key,value,description,updated_at from public.system_settings where organization_id=$1::uuid order by key`,[c.organizationId])]);return NextResponse.json({ok:true,branches:branches.rows,departments:depts.rows,sections:sections.rows,job_titles:titles.rows,roles:roles.rows,permissions:perms.rows,role_permissions:rolePerms.rows,settings:settings.rows});}catch(e){const x=jsonError(e);return NextResponse.json({ok:false,error:x.error},{status:x.status});}}
export async function POST(req:NextRequest){try{const c=await requireUser(),b=await req.json(),action=String(b?.action||'');
 if(action==='create_branch'){must(c,'branches.manage');const p=z.object({name:z.string().min(2),code:z.string().optional().default(''),city:z.string().optional(),address:z.string().optional(),phone:z.string().optional()}).parse(b);const r=await pool.query(`insert into public.branches(organization_id,name,code,city,address,phone,created_by) values($1::uuid,$2,$3,$4,$5,$6,$7::uuid) returning *`,[c.organizationId,p.name,codeOf(p),p.city||null,p.address||null,p.phone||null,c.user.id]);return NextResponse.json({ok:true,item:r.rows[0]});}
 if(action==='create_department'){must(c,'departments.manage');const p=z.object({name:z.string().min(2),code:z.string().optional().default(''),branch_id:z.string().uuid().nullable().optional(),parent_department_id:z.string().uuid().nullable().optional()}).parse(b);const r=await pool.query(`insert into public.departments(organization_id,name,code,branch_id,parent_department_id,created_by) values($1::uuid,$2,$3,$4::uuid,$5::uuid,$6::uuid) returning *`,[c.organizationId,p.name,codeOf(p),p.branch_id||null,p.parent_department_id||null,c.user.id]);return NextResponse.json({ok:true,item:r.rows[0]});}
 if(action==='create_section'){must(c,'sections.manage');const p=z.object({name:z.string().min(2),code:z.string().optional().default(''),department_id:z.string().uuid()}).parse(b);const r=await pool.query(`insert into public.sections(organization_id,name,code,department_id,created_by) values($1::uuid,$2,$3,$4::uuid,$5::uuid) returning *`,[c.organizationId,p.name,codeOf(p),p.department_id,c.user.id]);return NextResponse.json({ok:true,item:r.rows[0]});}
 if(action==='create_job_title'){must(c,'job_titles.manage');const p=z.object({name:z.string().min(2),code:z.string().optional().default(''),description:z.string().optional()}).parse(b);const r=await pool.query(`insert into public.job_titles(organization_id,name,code,description,created_by) values($1::uuid,$2,$3,$4,$5::uuid) returning *`,[c.organizationId,p.name,codeOf(p),p.description||null,c.user.id]);return NextResponse.json({ok:true,item:r.rows[0]});}
 if(action==='save_setting'){must(c,'settings.manage');const p=z.object({key:z.string().min(1),value:z.any(),description:z.string().optional()}).parse(b);await pool.query(`insert into public.system_settings(organization_id,key,value,description,updated_by) values($1::uuid,$2,$3::jsonb,$4,$5::uuid) on conflict(organization_id,key) do update set value=excluded.value,description=excluded.description,updated_by=excluded.updated_by,updated_at=now()`,[c.organizationId,p.key,JSON.stringify(p.value),p.description||null,c.user.id]);return NextResponse.json({ok:true});}
 if(action==='create_role'){must(c,'roles.manage');const p=z.object({code:z.string().min(2).regex(/^[a-z0-9_]+$/),name_ar:z.string().min(2),description:z.string().optional()}).parse(b);const r=await pool.query(`insert into public.roles(organization_id,code,name_ar,description,is_system,active) values($1::uuid,$2,$3,$4,false,true) returning *`,[c.organizationId,p.code,p.name_ar,p.description||null]);return NextResponse.json({ok:true,item:r.rows[0]});}
 if(action==='set_role_permission'){must(c,'roles.manage');const p=z.object({role_id:z.string().uuid(),permission_id:z.string().uuid(),enabled:z.boolean()}).parse(b);const chk=await pool.query(`select 1 from public.roles where id=$1::uuid and (organization_id is null or organization_id=$2::uuid)`,[p.role_id,c.organizationId]);if(!chk.rows[0])throw new Error('INVALID_ROLE');if(p.enabled)await pool.query(`insert into public.role_permissions(role_id,permission_id) values($1::uuid,$2::uuid) on conflict do nothing`,[p.role_id,p.permission_id]);else await pool.query(`delete from public.role_permissions where role_id=$1::uuid and permission_id=$2::uuid`,[p.role_id,p.permission_id]);return NextResponse.json({ok:true});}
 if(action==='set_user_permission_override'){must(c,'roles.manage');const p=z.object({user_id:z.string().uuid(),permission_id:z.string().uuid(),effect:z.enum(['allow','deny']).nullable()}).parse(b);if(p.effect)await pool.query(`insert into public.user_permission_overrides(user_id,permission_id,organization_id,effect,created_by) values($1::uuid,$2::uuid,$3::uuid,$4,$5::uuid) on conflict(user_id,permission_id,organization_id) do update set effect=excluded.effect,created_by=excluded.created_by,created_at=now()`,[p.user_id,p.permission_id,c.organizationId,p.effect,c.user.id]);else await pool.query(`delete from public.user_permission_overrides where user_id=$1::uuid and permission_id=$2::uuid and organization_id=$3::uuid`,[p.user_id,p.permission_id,c.organizationId]);return NextResponse.json({ok:true});}
 throw new Error('INVALID_ACTION');}catch(e){const x=jsonError(e);return NextResponse.json({ok:false,error:x.error},{status:x.status});}}
